spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    from: ${GMAIL_USERNAME} # 可選: 設定預設寄件人 (如果郵件中沒有明確設定 from)
    
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT}

logging:
  level:
    root: DEBUG
  file:
    name: logs/app.log

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}          # JWT Token 有效期 (例如：24 小時，單位毫秒)
  refresh-expiration: ${JWT_REFRESH_EXPIRATION} # Refresh Token 有效期 (例如：7 天，單位毫秒)

# Mailjet Configuration
mailjet:
  api-key: ${MAILJET_API_KEY}
  secret-key: ${MAILJET_SECRET_KEY}
  sender-email: ${MAILJET_SENDER_EMAIL} # 你在 Mailjet 設定的發信人 Email
  sender-name: ${MAILJET_SENDER_NAME} # 發信人名稱

app:
  base-url: ${BASE_URL}